lst = list(map(int, input("Enter numbers: ").split()))
print("Length:", len(lst))
print("Sum:", sum(lst))
print("Max:", max(lst))
print("Min:", min(lst))
even = [x for x in lst if x % 2 == 0]
odd = [x for x in lst if x % 2 != 0]
print("Even:", even)
print("Odd:", odd)
unique_sorted = sorted(set(lst))
print("Unique Sorted:", unique_sorted)
sorted_lst = sorted(lst)
print("Second Smallest:", sorted_lst[1])
print("Second Largest:", sorted_lst[-2])
x = int(input("Enter element to count: "))
print("Count:", lst.count(x))
y = int(input("Enter element to find index: "))
print("Index:", lst.index(y) if y in lst else "Not found")
print("Reversed:", lst[::-1])
no_neg = [i for i in lst if i >= 0]
print("Without negatives:", no_neg)
avg = sum(lst) / len(lst)
print("Average:", avg)
print("Greater than avg:", [i for i in lst if i > avg])
print("Descending:", sorted(lst, reverse=True))
tup = tuple(lst)
print("Tuple:", tup)
print("this is the result of the given program in this list")