t = tuple(map(int, input("Enter tuple elements: ").split()))
print("Length:", len(t))
print("Max:", max(t), "Min:", min(t))
x = int(input("Enter element: "))
print("Count:", t.count(x))
print("Index:", t.index(x) if x in t else "Not found")
lst = list(t)
lst.append(100)
lst.remove(lst[0])
t = tuple(lst)
print("Modified Tuple:", t)
print("Ascending:", sorted(t))
print("Descending:", sorted(t, reverse=True))
print("No duplicates:", tuple(set(t)))
